---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  clusterIP: None
  ports:
  - name: http-lagom-api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: userservice